### ISSUE TITLE
Adding linting

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene-rfcs#2]
Per @tihuan 's suggestion, add linting to the Markdown files that will be added to this repo. There are a couple ideas:

1. Github's new super-linter - to lint PR
2. A Node based CLI tool: markdownlint-cli, which powers Github's super-linter - to set up pre-commit hook to autofix errors

**Comment by tihuan** [comment]
Thanks for creating the issue, @maniarathi 🤩 !

**Comment by tihuan** [comment]
1. https://github.com/github/super-linter

This one we probably just need to follow the repo's doc to see how to enable Markdown linting lol

2. https://github.com/DavidAnson/markdownlint 

I think instead of `markdownlint-cli`, we might need to use just `markdownlint`!

So the steps for setting up linting precommit could be:

1. Add `package.json` via `npm init` in the root of this directory // this should create package.json
2. It seems like a `package.json` **must** contain name and version, so probably some placeholder will do [doc](https://docs.npmjs.com/creating-a-package-json-file)
3. `npm i --save-dev prettier markdownlint` 
4. `npx mrm lint-staged` [doc](https://github.com/okonet/lint-staged)
5. Configure `package.json` to lint markdown:

```ts
// package.json
{
  // { other code ... },
  "lint-staged": {
    "*.md": ["markdownlint", "prettier --write"]
  }
}
```
6. Now it pre-commit hook should be set up, so we can verify it works by editing an .md file that could be fixed by the linter 
7. Now try to commit it via `git add . && git commit -m 'test linter`
8. See if the .md file is now fixed and commited!

**Comment by tihuan** [comment]
(I can also help set up the pre-commit hook portion if that's easier 😆 )

**Comment by maniarathi** [comment]
Haha, do you mind too much if you go ahead and do it? :) It seems like you're 70% there with the detailed information above! 😃

**Comment by tihuan** [comment]
Ahaha totally! I'll work on that now!

**Comment by tihuan** [comment]
@maniarathi Oh can I haz write access please 😄 🙏 ? Ready for a PR! Thank you! 🎉

**Comment by maniarathi** [comment]
Ahh sorry! Should be good now!

**Comment by tihuan** [comment]
Hurray! Thanks @maniarathi ! PR out 🎉  https://github.com/chanzuckerberg/cellxgene-rfcs/pull/3
